export const TAG_LIST_REQUEST="TAG_LIST_REQUEST";
export const TAG_LIST_SUCCES="TAG_LIST_SUCCES";
export const TAG_LIST_FAIL="TAG_LIST_SUCCES";

export const TAG_ADD_REQUEST="TAG_ADD_REQUEST";
export const TAG_ADD_SUCCES="TAG_ADD_SUCCES";
export const TAG_ADD_FAIL="TAG_ADD_SUCCES";

export const TAG_EDIT_REQUEST="TAG_EDIT_REQUEST";
export const TAG_EDIT_SUCCES="TAG_EDIT_SUCCES";
export const TAG_EDIT_FAIL="TAG_EDIT_SUCCES";

export const TAG_UPDATE_REQUEST="TAG_EDIT_REQUEST";
export const TAG_UPDATE_SUCCES="TAG_EDIT_SUCCES";
export const TAG_UPDATE_FAIL="TAG_EDIT_SUCCES";

export const TAG_DELETE_REQUEST="TAG_DELETE_REQUEST";
export const TAG_DELETE_SUCCES="TAG_DELETE_SUCCES";
export const TAG_DELETE_FAIL="TAG_DELETE_SUCCES";